DROP TABLE IF EXISTS USER_BASICINFO;

CREATE TABLE USER_BASICINFO (
            USER_NAME VARCHAR(250) NOT NULL,
            PASSWORD VARCHAR(250) NOT NULL,
            EMAIL VARCHAR(250) NOT NULL,
            AGE INT(20) NOT NULL,
            GENDER VARCHAR(250) NOT NULL
);
